apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-deployment4
    labels:
       app: nginx-app1
spec:
    replicas: 3
    selector:
       matchLabels:
           app: nginx-app1
    template:
       metadata:
           labels:
             app: nginx-app1
       spec:
            containers:
            - name: nginx-controller
              image: skumar24/webapp:$BUILD_NUMBER
              ports:
              - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
     name: auth-svc1
     labels:
        app: nginx-app1
spec:
    selector:
        app: nginx-app1
    type: NodePort
    ports:
    - nodePort: 31156
      port: 80
      targetPort: 80
