apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-deployment
    labels:
       app: nginx-app
spec:
    replicas: 3
    selector:
       matchLabels:
           app: nginx-app
    template:
       metadata:
           labels:
             app: nginx-app
       spec:
            containers:
            - name: nginx-controller
              image: skumar24/webapp:${env.BUILD_ID}
              ports:
              - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
     name: auth-svc
     labels:
        app: nginx-app
spec:
    selector:
        app: nginx-app
    type: NodePort
    ports:
    - nodePort: 31155
      port: 80
      targetPort: 80
